Entity/ArticleRepository.php
<?php

namespace Zorbus\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticles()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a, c, t FROM ZorbusArticleBundle:Article a LEFT JOIN a.categories c LEFT JOIN a.tags t WHERE a.is_enabled = :is_enabled AND a.status <> :draft ORDER BY a.date_published DESC'
        )
                ->setParameter('is_enabled', true)
                ->setParameter('draft', 'draft')
                ->getResult();
    }
    public function getArticlesWithTag($tag)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a, c, t FROM ZorbusArticleBundle:Article a LEFT JOIN a.categories c JOIN a.tags t WITH t.slug = :tag WHERE a.is_enabled = :is_enabled AND a.status <> :draft ORDER BY a.date_published DESC'
        )
                ->setParameter('is_enabled', true)
                ->setParameter('draft', 'draft')
                ->setParameter('tag', $tag)
                ->getResult();
    }
    public function getArticlesWithCategory($category)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a, c, t FROM ZorbusArticleBundle:Article a JOIN a.categories c WITH c.slug = :category LEFT JOIN a.tags t WHERE a.is_enabled = :is_enabled AND a.status <> :draft ORDER BY a.date_published DESC'
        )
                ->setParameter('is_enabled', true)
                ->setParameter('draft', 'draft')
                ->setParameter('category', $category)
                ->getResult();
    }
}

Controller/BlockController.php
<?php

namespace Zorbus\ArticleBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class BlockController extends Controller
{

    public function articleAction($block)
    {
        $parameters = json_decode($block->getParameters());
        $article = $this->getDoctrine()->getRepository('ZorbusArticleBundle:Article')->find($parameters->article);

        return $this->render('ZorbusArticleBundle:Block:article.html.twig', array(
                    'block' => $block, 'article' => $article
                ));
    }
    public function categoryAction($block)
    {
        $parameters = json_decode($block->getParameters());
        $category = $this->getDoctrine()->getRepository('ZorbusArticleBundle:Category')->find($parameters->category);

        return $this->render('ZorbusArticleBundle:Block:category.html.twig', array(
                    'block' => $block, 'category' => $category
                ));
    }

}

Resources/views/Block/article.html.twig
<div class="row-fluid">
    <h1>{{ article.title }}</h1>
    {% if article.subtitle|length > 0 %}
        <h2>{{ article.subtitle }}</h2>
    {% endif %}

    <div class="row"><strong>{{ article.resume | raw }}</strong></div>

    {{ article.body | raw }}

    <div class="row">
        <span></span>
        <span class="well span4">
        {% for category in article.categories %}
            <span class="badge badge-info">{{ category.name }}</span>
        {% endfor %}
        </span>

        <span class="well span4">
        {% for tag in article.tags %}
            <span class="label label-info">{{ tag.name }}</span>
        {% endfor %}
        </span>
    </div>

    <p><small>{{ article.datePublished | date('Y-m-d') }}</small></p>
</div>

Resources/views/Block/category.html.twig
<div class="row-fluid">
    <h1>{{ category.name }}</h1>

    <ul>
    {% for article in category.articles %}
        <li>{{ article.title }}: {{ article.datePublished | date('Y-m-d') }}</li>
    {% else %}
        <li>No articles in this category.</li>
    {% endfor %}
    </ul>
</div>